version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/flask_test

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: codedeploy/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 300
      runas: ubuntu
