name: Deploy to AWS via CodeDeploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: safebattery-s3
  APPLICATION_NAME: SafeBattery-CodeDeploy-AI
  DEPLOYMENT_GROUP: SafeBattery-CodeDeploy-AI-Group

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Zip and upload to S3
        run: |
          zip -r deployment-${{ github.sha }}.zip .
          aws s3 cp deployment-${{ github.sha }}.zip s3://$S3_BUCKET/deployment-${{ github.sha }}.zip --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name $APPLICATION_NAME \
            --deployment-group-name $DEPLOYMENT_GROUP \
            --s3-location bucket=$S3_BUCKET,key=deployment-${{ github.sha }}.zip,bundleType=zip \
            --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
